spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # API Routes
            - id: client-service
              uri: http://client-service:9080
              predicates:
                - Path=/api/v1/clients/**, /api/v1/auth/**

            - id: account-service
              uri: http://account-service:9090
              predicates:
                - Path=/api/v1/accounts/**, /api/v1/movements/**, /api/v1/reports/**

            # Documentation Routes
            - id: client-service-docs
              uri: http://client-service:9080
              predicates:
                - Path=/v3/api-docs/client-service
              filters:
                - RewritePath=/v3/api-docs/client-service, /v3/api-docs

            - id: account-service-docs
              uri: http://account-service:9090
              predicates:
                - Path=/v3/api-docs/account-service
              filters:
                - RewritePath=/v3/api-docs/account-service, /v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: Client Service
        url: /v3/api-docs/client-service
      - name: Account Service
        url: /v3/api-docs/account-service

server:
  port: 8080